### ISSUE TITLE
Where is the doc to set up kube-aggregator, especially register heapster into kube-aggregator for autoscaler

### ISSUE THREAD

**Issue by luckyfengyong** [kubernetes/kube-aggregator#7]
Where is doc to set up kube-aggregator,  especially register heapster into kube-aggregator for autoscaler. 
I saw some artifacts in https://github.com/kubernetes/kube-aggregator/tree/master/artifacts, however without doc. Not sure whether those could be used direclty.
BTW, I set up the k8s 1.6 cluster by kubeadm.

**Comment by luxas** [comment]
@luckyfengyong You might find this project interesting. There you'll find example APIServiceRegistrations

**Comment by luckyfengyong** [comment]
@luxas thanks for the reply. Can you help to guide me where to find the example of APIServiceRegistrations? I try to search the repo for the keyword of APIServiceRegistrations, but with no luck. :-(

**Comment by luckyfengyong** [comment]
It seems the patch of https://github.com/kubernetes/kubernetes/pull/42911 is much easier. Thanks @luxas The https://github.com/luxas/kubeadm-workshop helps a lot.

**Comment by rootsongjc** [comment]
@luckyfengyong Are you still using kubernetes 1.6? How do you solve this problem?
