### ISSUE TITLE
handler_proxy_test.go failing on several PRs

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kube-aggregator#8]
Common error:
```
handler_proxy_test.go:328: invalid hostname + insecure: expected called=true, got false
testing.go:610: race detected during execution of test
```

Examples:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49051/pull-kubernetes-unit/42307/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49346/pull-kubernetes-unit/42303/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49238/pull-kubernetes-unit/42301/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48784/pull-kubernetes-unit/42297/

**Comment by lavalamp** [comment]
@liggitt already fixed this in https://github.com/kubernetes/kubernetes/pull/49404

**Comment by mtaufen** [comment]
Great, thanks @lavalamp!
